export const TRIAGE_COPY = {
  title: "Quick check",
  sub: (n: number) => `${n} to review`,
  empty: "You’re all caught up",
  close: "Close",
  chipUncategorised: "Uncategorised",
  chipDuplicate: "Duplicate suspect",
  chipLowConfidence: "Low confidence",
  suggested: (cat: string) => `Suggested: ${cat}`,
  categorise: "Categorise",
  confirm: "Confirm",
  ignore: "Ignore",
  viewDuplicate: "View duplicate",
  bulkIgnoreLow: "Ignore all low-confidence",
  bulkIgnoreLowConfirm: (k: number) => `Ignore ${k} low-confidence items?`,
  bulkCancel: "Cancel",
  toastCategorised: (cat: string) => `Categorised as ${cat}`,
  toastConfirmed: "Confirmed",
  toastIgnored: "Ignored",
  undo: "Undo",
  pickerSearch: "Search categories",
  pickerEmpty: "No categories match",
  pickerManage: "Manage categories…",
  loading: "Loading exceptions…",
  loadError: "Couldn’t load exceptions — try again",
  actionError: "Couldn’t save that change — try again",
  undoError: "Couldn’t undo — try again",
  unavailable: "Unavailable right now",
} as const;
