export const INV_COPY = {
  title: "Invoices",
  ctaNew: "New",
  emptyTitle: "No invoices yet",
  emptyDropTitle: "Drop PDF or image",
  emptyDropSub: "We'll draft an invoice you can edit.",
  emptyDropChoose: "Choose file",
  emptyCreateTitle: "Create invoice",
  emptyCreateCta: "New",
  sheetTitle: "New invoice",
  sheetHow: "How do you want to start?",
  dropTitle: "Drop PDF or image",
  dropSub: "We'll draft an invoice you can edit.",
  dropChoose: "Choose file",
  dropProgress: "Creating draft…",
  dropToast: "Draft created — check details",
  quickCustomer: "Customer",
  quickAmount: "Amount (₦)",
  quickVat: "Add VAT 7.5%",
  quickDesc: "Description",
  quickDescPlaceholder: "Optional one-liner",
  quickSaveDraft: "Save draft",
  quickIssue: "Issue",
  fullLink: "Need line items / discounts? Full form",
  clientCreate: (name: string) => `Create “${name}”`,
  clientName: "Client name",
  clientEmail: "Email",
  clientPhone: "Phone",
  clientSave: "Save client",
  clientSearch: "Search or type a name…",
} as const;
