export const DOCS_COPY = {
  title: "Documents",
  ctaUpload: "Upload",
  emptyTitle: "Drop PDF, image, or CSV",
  emptySub: "Attach to a transaction, invoice, or expense anytime.",
  emptyChoose: "Choose file",
  emptyHint: "Bank statements? Drop them on Books or Dashboard.",
  emptyHintBooks: "Books",
  emptyHintDashboard: "Dashboard",
  emptyStatementsK: "Statements",
  emptyStatementsV: "Books / Dashboard DropZone → Import AUTO",
  emptyOtherK: "Other files",
  emptyOtherV: "Documents library → Attach later",
  toastStatementKeep: "Keep in Documents",
  stripTitle: "Drop PDF, image, or CSV",
  stripChoose: "Choose file",
  filterAll: "All",
  filterPdf: "PDF",
  filterImages: "Images",
  filterCsv: "CSV",
  filterAttached: "Attached",
  filterUnattached: "Unattached",
  rowUnattached: "Unattached",
  rowAttach: "Attach",
  rowPreview: "Preview",
  rowDownload: "Download",
  rowDelete: "Delete",
  toastUploaded: (filename: string) => `${filename} uploaded`,
  toastAttachCta: "Attach",
  toastAttached: (record: string) => `Attached to ${record}`,
  toastDeleted: (filename: string) => `${filename} deleted`,
  toastReject: "Use PDF, image, or CSV.",
  toastTooLarge: "File size must be less than 10MB",
  toastFailed: "Upload failed. Please try again.",
  toastStatement: "Looks like a bank statement — Import to Books?",
  toastStatementCta: "Import to Books",
  progress: "Uploading…",
  attachTitle: "Attach file",
  attachLinkTo: "Link to",
  attachTxn: "Transaction",
  attachInvoice: "Invoice",
  attachExpense: "Expense",
  attachSearch: "Type to find…",
  attachCancel: "Cancel",
  attachConfirm: "Attach",
  attachDrop: "Drop PDF, image, or CSV",
  attachRecent: "Recent uploads",
  attachChoose: "Choose",
  deleteTitle: (filename: string) => `Delete ${filename}?`,
  deleteBody:
    "This removes the file from Documents. Links on transactions, invoices, or expenses are cleared.",
  deleteConfirm: "Delete",
  moreLabel: "Documents",
  detailCta: "Attach file",
} as const;

export const DOCS_ACCEPT = ".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx,.xls";
export const DOCS_MAX_BYTES = 10 * 1024 * 1024;
