export const BIZ_COPY = {
  title: "Business profile",
  sub: "Shown on invoices and documents you send.",
  legalName: "Legal name",
  address: "Address",
  address1: "Address line 1",
  address2: "Address line 2 (optional)",
  city: "City",
  state: "State",
  country: "Country",
  email: "Email",
  phone: "Phone",
  tin: "TIN",
  vat: "VAT number",
  contact: "Contact",
  taxIds: "Tax IDs (optional)",
  logoDeferred: "Logo upload coming later — invoices use your legal name only for now.",
  save: "Save",
  cancel: "Cancel",
  nudgeTitle: "Add your business details",
  nudgeSub: "Your name and address appear on PDFs you send.",
  nudgeCta: "Open Settings",
  blockLegalName: "Add your business name in Settings before issuing",
  toastSavedIncomplete: "Saved — add address to finish your invoice header",
  toastSaved: "Business profile saved",
} as const;

export const CLIENTS_COPY = {
  title: "Clients",
  new: "New client",
  empty: "No clients yet — create one when you issue an invoice, or add here.",
  search: "Search clients",
  name: "Name",
  email: "Email",
  city: "City",
  phone: "Phone",
  address1: "Address line 1",
  address2: "Address line 2 (optional)",
  state: "State",
  country: "Country",
  save: "Save",
  cancel: "Cancel",
  hide: "Hide",
  usedOnInvoices: "Used on invoices",
  hideConfirm: "Hide this client from new invoices? Existing issued invoices keep their snapshot.",
  deleteBlocked: "This client is used on issued invoices and cannot be deleted.",
} as const;
